// C STEP LAB — 2,000問 / 未回答ランダム出題 / 端末内保存
const LEVEL_SIZE = 250;
const pick=(a,i)=>a[((i%a.length)+a.length)%a.length];
const mc=(id,q,c,a,e,code='')=>({id,q,c,a,e,code});
const cq=(id,q,starter,keys,e)=>({id,q,type:'code',starter,keys,e});
function makeLevel(level){const qs=[];for(let i=0;i<LEVEL_SIZE;i++){const a=2+(i*7)%18,b=1+(i*11)%12,n=2+(i*5)%9,k=1+(i*3)%5;let q;
 if(level===0){switch(i%5){case 0:q=mc(`L0-${i}`,`${a} + ${b} の結果は？`,[String(a+b),String(a-b),String(a*b),String(Math.floor(a/b))],0,`整数の加算なので ${a}+${b}=${a+b} です。`,`int x=${a}, y=${b};\nprintf("%d", x+y);`);break;case 1:q=mc(`L0-${i}`,`変数 x を ${a} で初期化する正しい書き方は？`,[`int x = ${a};`,`int = x ${a};`,`x int = ${a};`,`int ${a} = x;`],0,`int x = ${a}; の形で、整数型の変数を宣言と同時に初期化します。`);break;case 2:q=mc(`L0-${i}`,`このプログラムが表示する値は？`,[String(a),String(b),String(a+b),String(a*b)],2,`x+y を表示するため答えは ${a+b} です。`,`int x=${a};\nint y=${b};\nprintf("%d", x+y);`);break;case 3:q=mc(`L0-${i}`,`整数 ${a} を表示するとき使う書式指定子は？`,['%d','%f','%s','%c'],0,'%d は int 型の整数を表示するときに使います。');break;default:q=mc(`L0-${i}`,`x=${a} のあと x=x+${b}; を実行すると x は？`,[String(a),String(b),String(a+b),String(a*b)],2,`右辺の ${a}+${b} を計算して x に代入するので ${a+b} です。`,`int x=${a};\nx=x+${b};`);} }
 if(level===1){switch(i%5){case 0:q=mc(`L1-${i}`,`この for 文は何回実行される？`,[`${n-1}回`,`${n}回`,`${n+1}回`,`無限`],1,`i=0 から i=${n-1} までなので ${n} 回です。`,`for(int i=0; i<${n}; i++){\n  printf("C");\n}`);break;case 1:{let s=(i*13)%101,ans=s>=80?0:s>=60?1:2;q=mc(`L1-${i}`,`score=${s} のとき表示は？`,['A','B','C','何も表示されない'],ans,`${s} を上から順に条件判定すると ${pick(['A','B','C'],ans)} になります。`,`if(score>=80) printf("A");\nelse if(score>=60) printf("B");\nelse printf("C");`);break;}case 2:q=mc(`L1-${i}`,`i=${a} のとき「偶数」を判定する条件は？`,['i % 2 == 0','i / 2 == 0','i % 2 == 1','i = 2'],0,'2で割った余りが0なら偶数です。');break;case 3:q=mc(`L1-${i}`,`while 文で x を ${b} から0まで1ずつ減らす更新式は？`,['x++','x--','x+=2','x=0'],1,'x-- は x を1減らします。');break;default:q=mc(`L1-${i}`,`1から${n}まで for 文で回す条件として適切なのは？`,[`i<${n}`,`i<=${n}`,`i>${n}`,`i==${n}`],1,`${n} も含めるので i<=${n} とします。`,`for(int i=1; ???; i++)`);} }
 if(level===2){switch(i%5){case 0:{let arr=[a,b,a+b,a*b],idx=i%4;q=mc(`L2-${i}`,`data[${idx}] の値は？`,arr.map(String),idx,`配列は0番から数えるため data[${idx}] は ${arr[idx]} です。`,`int data[4]={${arr.join(', ')}};`);break;}case 1:q=mc(`L2-${i}`,`add(${a}, ${b}) の戻り値は？`,[String(a),String(b),String(a+b),String(a*b)],2,`return x+y なので ${a+b} が返ります。`,`int add(int x,int y){ return x+y; }`);break;case 2:q=mc(`L2-${i}`,`要素数 ${n} の配列 a の最後の添字は？`,[String(n),String(n-1),'0',String(n+1)],1,`添字は0から始まるので最後は ${n-1} です。`);break;case 3:q=mc(`L2-${i}`,`関数 square(${b}) の結果は？`,[String(b),String(b+2),String(b*b),String(b*2)],2,`${b}×${b}=${b*b} です。`,`int square(int n){ return n*n; }`);break;default:q=mc(`L2-${i}`,`配列 int a[${n}]; に格納できる int は何個？`,[String(n-1),String(n),String(n+1),'無制限'],1,`[${n}] は要素数 ${n} を表します。`);} }
 if(level===3){switch(i%5){case 0:q=mc(`L3-${i}`,'変数 x のアドレスを得る式は？',['x','*x','&x','x&'],2,'& はアドレス演算子です。');break;case 1:q=mc(`L3-${i}`,'int *p が指す値を取り出す式は？',['p','&p','*p','p*'],2,'*p でポインタ p の指す先の値を参照します。');break;case 2:q=mc(`L3-${i}`,'構造体変数 s のメンバ age にアクセスする式は？',['s->age','s.age','s::age','s&age'],1,'通常の構造体変数では . 演算子を使います。');break;case 3:q=mc(`L3-${i}`,'文字列の末尾を表す文字は？',["'\\0'","'\\n'","'0'","' '"] ,0,'Cの文字列はヌル文字 \\0 で終わります。');break;default:q=mc(`L3-${i}`,'構造体へのポインタ p からメンバ value にアクセスする式は？',['p.value','p->value','*p.value','p::value'],1,'構造体ポインタでは -> 演算子を使います。');} }
 if(level===4){switch(i%4){case 0:q=mc(`L4-${i}`,`0〜${n-1}を表示するため ??? は？`,[`i<=${n}`,`i<${n}`,`i>${n}`,`i==${n}`],1,`0から${n-1}までなので i<${n} です。`,`for(int i=0; ???; i++){ printf("%d ",i); }`);break;case 1:q=mc(`L4-${i}`,`${a} と ${b} を足して表示する ??? は？`,['x-y','x+y','x*y','x/y'],1,'加算演算子 + を使います。',`int x=${a},y=${b};\nprintf("%d", ???);`);break;case 2:q=mc(`L4-${i}`,'関数から値 n を返す ??? は？',['printf n','return n;','break n;','int n;'],1,'値を呼び出し元へ返すには return を使います。','int f(int n){\n  ???\n}');break;default:q=mc(`L4-${i}`,'配列 a の i 番目を表示する ??? は？',['a','a[i]','i[a][i]','&i'],1,'a[i] で i 番目の要素を参照します。','printf("%d", ???);');} }
 if(level===5){switch(i%5){case 0:q=mc(`L5-${i}`,'このコードのコンパイルエラー原因は？',['セミコロン不足','変数名','printf','main'],0,'変数宣言の末尾に ; が必要です。',`int x=${a}\nprintf("%d",x);`);break;case 1:q=mc(`L5-${i}`,'無限ループになりやすい原因は？',['i++ がある','条件が変化しない','printf がある','int を使う'],1,'ループ条件に関係する値が更新されないと終了できません。','int i=0;\nwhile(i<10){ printf("%d",i); }');break;case 2:q=mc(`L5-${i}`,'配列 int a[5] で範囲外アクセスは？',['a[0]','a[2]','a[4]','a[5]'],3,'有効な添字は0〜4です。a[5] は範囲外です。');break;case 3:q=mc(`L5-${i}`,'scanf で int x に入力するとき正しいのは？',['scanf("%d", x);','scanf("%d", &x);','scanf(x, "%d");','scanf("%f", &x);'],1,'scanf には変数のアドレス &x を渡します。');break;default:q=mc(`L5-${i}`,'比較したいのに代入になっている箇所は？',['if(x = 5)','printf','return 0','int x'],0,'等しいか比較するときは ==、= は代入です。','if(x = 5){ printf("OK"); }');} }
 if(level===6){switch(i%4){case 0:q=cq(`L6-${i}`,`整数 n を受け取り ${k+1} 倍して返す関数 mult を完成させてください。`,`int mult(int n){\n    // ここを書く\n}`,["return","n","*",String(k+1)],`例：return n * ${k+1};`);break;case 1:q=cq(`L6-${i}`,`整数 a と b の和を返す関数 add を完成させてください。`,`int add(int a,int b){\n    // ここを書く\n}`,["return","a","+","b"],'例：return a + b;');break;case 2:q=cq(`L6-${i}`,`0から${n-1}まで表示する for 文を書いてください。`,`for(                 ){\n    printf("%d ", i);\n}`,["i=0","i<"+n,"i++"],`例：for(int i=0; i<${n}; i++)`);break;default:q=cq(`L6-${i}`,'整数 x が正なら 1、それ以外なら 0 を返す処理を書いてください。','int positive(int x){\n    // ここを書く\n}',['if','x','>','0','return'],'if(x > 0) return 1; のように条件分岐できます。');} }
 if(level===7){switch(i%5){case 0:q=cq(`L7-${i}`,`1から${n}までの合計を計算して表示するCプログラムを最初から書いてください。`,'',['#include','stdio.h','main','for','printf'],`sumを0で初期化し、for文で1〜${n}を加算して表示します。`);break;case 1:q=cq(`L7-${i}`,`整数を1つ入力し、偶数なら「even」、奇数なら「odd」と表示するCプログラムを書いてください。`,'',['#include','main','scanf','%','2','printf'],'scanfで入力し、2で割った余りを if で判定します。');break;case 2:q=cq(`L7-${i}`,`整数を${n}個格納する配列を用意し、for文で全要素を表示するCプログラムを書いてください。`,'',['#include','main','int','[','for','printf'],'配列を宣言し、添字0から順に for 文で参照します。');break;case 3:q=cq(`L7-${i}`,`2つの整数を受け取り、大きい方を返す関数 max を含むCプログラムを書いてください。`,'',['#include','main','max','return','if','printf'],'max関数内で2つの値を比較して大きい方を return します。');break;default:q=cq(`L7-${i}`,`整数 n の階乗を求めて表示するCプログラムを書いてください。`,'',['#include','main','for','*','printf'],'積を1で初期化し、1からnまで順に掛けます。');} }
 qs.push(q);}return qs;}
const metas=[['Lv.0','はじめの一歩','出力・変数・計算'],['Lv.1','条件と繰り返し','if・for・while'],['Lv.2','配列と関数','配列・引数・return'],['Lv.3','中級C','ポインタ・文字列・構造体'],['Lv.4','穴埋め','コードの一部を完成'],['Lv.5','デバッグ','間違いを見つけて直す'],['Lv.6','実装練習','自分で一部を書く'],['Lv.7','コード全文チャレンジ','問題文から全部書く']];
const levels=metas.map((m,i)=>({n:m[0],title:m[1],desc:m[2],qs:makeLevel(i)}));
let state;try{state=JSON.parse(localStorage.getItem('cstep'))}catch(e){};state=Object.assign({xp:0,correct:0,total:0,completed:{},streak:0,bestStreak:0,solved:{},wrong:{}},state||{});state.solved=state.solved||{};state.wrong=state.wrong||{};
let li=0,current=null,selected=null;const $=id=>document.getElementById(id);function save(){localStorage.setItem('cstep',JSON.stringify(state))}function rank(){return state.xp>=3000?'S':state.xp>=1500?'A':state.xp>=600?'B':'C'}function rankInfo(){let r=rank(),min=r==='C'?0:r==='B'?600:r==='A'?1500:3000,max=r==='C'?600:r==='B'?1500:r==='A'?3000:3000;return{r,p:r==='S'?100:Math.min(100,Math.round((state.xp-min)/(max-min)*100)),next:r==='S'?'最高ランク到達！':`次のランクまで ${max-state.xp} XP`}}function toast(t){let el=$('toast');el.textContent=t;el.classList.remove('hidden');setTimeout(()=>el.classList.add('hidden'),1800)}
function solvedCount(i){return levels[i].qs.filter(q=>state.solved[q.id]).length}function unsolved(i){return levels[i].qs.filter(q=>!state.solved[q.id])}function home(){$('quiz').classList.add('hidden');$('home').classList.remove('hidden');let ri=rankInfo();$('heroRank').textContent=ri.r;$('xpBar').style.width=ri.p+'%';$('rankNext').textContent=ri.next;$('stats').innerHTML=`<div class=stat><div class=stat-icon>⚡</div><div><b>${state.xp}</b><small>XP</small></div></div><div class=stat><div class=stat-icon>🏆</div><div><b>${rank()}</b><small>ランク</small></div></div><div class=stat><div class=stat-icon>🎯</div><div><b>${state.total?Math.round(state.correct/state.total*100):0}%</b><small>正答率</small></div></div><div class=stat><div class=stat-icon>📚</div><div><b>${Object.keys(state.solved).length}</b><small>/ ${LEVEL_SIZE*levels.length} 問</small></div></div>`;let icons=['🌱','🔀','📦','🧠','🧩','🐞','🛠️','🚀'];$('levels').innerHTML=levels.map((l,i)=>{let done=solvedCount(i),all=done===l.qs.length;return `<button class=level onclick="start(${i})"><div class=level-icon>${icons[i]}</div><div><strong>${l.n} ${l.title}</strong><small>${l.desc}</small><small class=${all?'done':''}>${all?'✓ 全問クリア':`未回答 ${l.qs.length-done}問 / 全${l.qs.length}問`}</small></div><div class=level-no>${String(i+1).padStart(2,'0')}</div></button>`}).join('')}
window.start=i=>{li=i;nextRandom()};function nextRandom(){let pool=unsolved(li);if(!pool.length){state.completed[li]=true;save();alert('このレベルの250問をすべて解きました！\n進捗リセットをしない限り、解いた問題は再出題されません。');home();return}current=pool[Math.floor(Math.random()*pool.length)];show()}
function show(){selected=null;let l=levels[li],q=current,done=solvedCount(li);$('home').classList.add('hidden');$('quiz').classList.remove('hidden');$('levelBadge').textContent=`${l.n} ${l.title}`;$('progress').textContent=`未回答 ${l.qs.length-done} / ${l.qs.length}`;$('questionBar').style.width=(done/l.qs.length*100)+'%';$('streak').textContent=`🔥 ${state.streak||0} COMBO`;$('question').textContent=q.q;$('feedback').className='feedback hidden';$('nextBtn').classList.add('hidden');$('submitBtn').classList.remove('hidden');$('code').classList.toggle('hidden',!q.code);$('code').querySelector('code').textContent=q.code||'';$('choices').innerHTML='';$('answer').classList.add('hidden');if(q.type==='code'){$('answer').classList.remove('hidden');$('answer').value=q.starter||''}else{$('choices').innerHTML=q.c.map((x,i)=>`<button class=choice data-i=${i}>${String.fromCharCode(65+i)}：${x}</button>`).join('');document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{document.querySelectorAll('.choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selected=+b.dataset.i})}}
$('submitBtn').onclick=()=>{let q=current,ok;if(q.type==='code'){let v=$('answer').value.toLowerCase().replace(/\s+/g,'');ok=q.keys.every(k=>v.includes(k.toLowerCase().replace(/\s+/g,'')))}else{if(selected===null){alert('回答を選んでください');return}ok=selected===q.a}state.total++;state.solved[q.id]=true;if(ok){state.correct++;state.xp+=20;state.streak=(state.streak||0)+1;state.bestStreak=Math.max(state.bestStreak||0,state.streak);toast(`正解！ +20 XP  🔥 ${state.streak} COMBO`)}else{state.streak=0;state.wrong[q.id]=true}$('feedback').className='feedback '+(ok?'ok':'ng');$('feedback').innerHTML=`<strong>${ok?'正解！ 🎉':'もう一歩！'}</strong><br>${q.e}<br><b>${ok?'+20 XP':'この問題は解答済みとして記録されます'}</b>`;save();$('submitBtn').classList.add('hidden');$('nextBtn').classList.remove('hidden')};
$('nextBtn').onclick=nextRandom;$('backBtn').onclick=home;$('resetBtn').onclick=()=>{if(confirm('XP・正答率・解答済み問題を含む学習記録をすべてリセットしますか？')){localStorage.removeItem('cstep');location.reload()}};home();

// ===== C STEP LAB+ extensions =====
state.byLevel=state.byLevel||{};state.days=state.days||{};state.achievements=state.achievements||{};state.lastLevel=state.lastLevel??0;state.hints=state.hints||0;state.examBest=state.examBest||0;
let mode='normal',examPool=[],examIndex=0,examCorrect=0,examStats={};
const today=()=>new Date().toLocaleDateString('sv-SE');
function dayState(){let d=today();state.days[d]=state.days[d]||{solved:0,correct:0,xp:0};return state.days[d]}
function levelStat(i){state.byLevel[i]=state.byLevel[i]||{total:0,correct:0};return state.byLevel[i]}
const achievementDefs=[['first','🌱','最初の一歩',s=>s.total>=1],['ten','🔟','10問突破',s=>s.total>=10],['hundred','💯','100問突破',s=>s.total>=100],['combo5','🔥','5コンボ',s=>s.bestStreak>=5],['combo20','⚡','20コンボ',s=>s.bestStreak>=20],['xp1000','💎','1000 XP',s=>s.xp>=1000],['rankS','👑','Sランク',s=>rank()==='S'],['exam80','🎓','試験80点',s=>s.examBest>=80],['review','🩹','復習開始',s=>s.achievements.review],['all','🚀','2000問制覇',s=>Object.keys(s.solved).length>=2000]];
function updateAchievements(){achievementDefs.forEach(([id,,,fn])=>{if(fn(state))state.achievements[id]=true})}
const oldHome=home;home=function(){updateAchievements();oldHome();renderPlus();save()};
function renderPlus(){let d=dayState();$('dailyBadge').textContent=`今日 ${d.solved}問`;$('daily').innerHTML=mission('5問解く',d.solved,5,'📘')+mission('3問正解',d.correct,3,'🎯')+mission('100 XP獲得',d.xp,100,'⚡');let unlocked=achievementDefs.filter(x=>state.achievements[x[0]]).length;$('achievementCount').textContent=`${unlocked}/${achievementDefs.length}`;$('achievements').innerHTML=achievementDefs.map(([id,ic,name])=>`<div class="achievement ${state.achievements[id]?'unlocked':''}"><b>${ic}</b><small>${name}</small></div>`).join('');$('analytics').innerHTML=`<div class="analytics-bars">${levels.map((l,i)=>{let s=levelStat(i),pct=s.total?Math.round(s.correct/s.total*100):0;return `<div class="a-row"><span>${l.n} ${l.title}</span><div class="a-track"><i style="width:${pct}%"></i></div><b>${pct}%</b></div>`}).join('')}</div>`}
function mission(name,val,max,ic){let p=Math.min(100,val/max*100);return `<div class="mission"><b>${ic}</b><div><span>${name}　${Math.min(val,max)}/${max}</span><div class="mission-track"><i style="width:${p}%"></i></div></div>${val>=max?'✅':''}</div>`}
function randomUnsolvedAny(){let candidates=[];levels.forEach((l,i)=>unsolved(i).length&&candidates.push(i));if(!candidates.length){toast('全2,000問クリア！');return}mode='normal';start(candidates[Math.floor(Math.random()*candidates.length)])}
$('continueBtn').onclick=randomUnsolvedAny;
$('reviewBtn').onclick=()=>{let ids=Object.keys(state.wrong);if(!ids.length){toast('復習する間違い問題はありません');return}state.achievements.review=true;mode='review';let id=ids[Math.floor(Math.random()*ids.length)],n=+id.match(/^L(\d)/)[1];li=n;current=levels[n].qs.find(q=>q.id===id);show()};
$('examBtn').onclick=()=>{mode='exam';examPool=[];for(let i=0;i<20;i++){let n=i%levels.length;let arr=levels[n].qs;examPool.push({li:n,q:arr[Math.floor(Math.random()*arr.length)]})}examPool.sort(()=>Math.random()-.5);examIndex=0;examCorrect=0;examStats={};loadExam()};
function loadExam(){if(examIndex>=examPool.length){finishExam();return}li=examPool[examIndex].li;current=examPool[examIndex].q;show()}
const oldShow=show;show=function(){oldShow();$('modeBadge').textContent=mode==='exam'?`模擬試験 ${examIndex+1}/20`:mode==='review'?'間違い復習':'通常学習';$('hintBtn').classList.toggle('hidden',mode==='exam');$('hint').classList.add('hidden');if(mode==='exam'){$('progress').textContent=`第 ${examIndex+1} 問 / 20`;$('questionBar').style.width=(examIndex/20*100)+'%'}};
$('hintBtn').onclick=()=>{state.hints++;let q=current;let txt=q.type==='code'?'必要なキーワードを考え、処理を小さく分けて書いてみよう。':`選択肢を1つずつコードの動きと照らし合わせよう。`;if(q.code)txt+=' コードは上から順番に値の変化を追うのがコツです。';$('hint').textContent='💡 '+txt;$('hint').classList.remove('hidden');save()};
const oldSubmit=$('submitBtn').onclick;$('submitBtn').onclick=()=>{let beforeCorrect=state.correct,beforeTotal=state.total,beforeXp=state.xp;oldSubmit();if(state.total===beforeTotal)return;let ok=state.correct>beforeCorrect,ls=levelStat(li),ds=dayState();ls.total++;if(ok)ls.correct++;ds.solved++;if(ok)ds.correct++;ds.xp+=state.xp-beforeXp;if(mode==='review'&&ok)delete state.wrong[current.id];if(mode==='exam'){examStats[li]=examStats[li]||{t:0,c:0};examStats[li].t++;if(ok){examStats[li].c++;examCorrect++}}updateAchievements();save()};
$('nextBtn').onclick=()=>{if(mode==='exam'){examIndex++;loadExam()}else if(mode==='review'){let ids=Object.keys(state.wrong);if(!ids.length){toast('間違い問題をすべて復習しました！');mode='normal';home();return}let id=ids[Math.floor(Math.random()*ids.length)],n=+id.match(/^L(\d)/)[1];li=n;current=levels[n].qs.find(q=>q.id===id);show()}else nextRandom()};
function finishExam(){let score=examCorrect*5;state.examBest=Math.max(state.examBest,score);updateAchievements();save();$('quiz').classList.add('hidden');$('home').classList.add('hidden');$('examResult').classList.remove('hidden');$('examScore').textContent=`${score}点`;$('examBreakdown').innerHTML=Object.keys(examStats).map(i=>{let s=examStats[i];return `<div class="result-row"><span>${levels[i].n} ${levels[i].title}</span><b>${s.c}/${s.t}</b></div>`}).join('')+`<p>${score>=80?'🎉 合格ライン！この調子です。':score>=60?'あと少し。正答率の低いレベルを復習しよう。':'基礎レベルから復習すると伸びやすいです。'}</p>`}
$('resultHome').onclick=()=>{$('examResult').classList.add('hidden');mode='normal';home()};
$('backBtn').onclick=()=>{$('examResult').classList.add('hidden');mode='normal';home()};
$('exportBtn').onclick=()=>{let blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`c-step-lab-backup-${today()}.json`;a.click();URL.revokeObjectURL(a.href)};
$('importFile').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let s=JSON.parse(r.result);if(typeof s!=='object'||s===null)throw 0;localStorage.setItem('cstep',JSON.stringify(s));alert('学習データを復元しました。');location.reload()}catch{alert('このバックアップファイルは読み込めません。')}};r.readAsText(f)};
// remember selected level
const oldStart=window.start;window.start=i=>{state.lastLevel=i;save();mode='normal';oldStart(i)};
home();
