const levels=[
{n:'Lv.0',title:'はじめの一歩',desc:'出力・変数・計算',qs:[
{q:'画面に Hello と表示する関数は？',c:['scanf','printf','return','include'],a:1,e:'printf は文字や数値を画面へ出力するために使います。'},
{q:'次の結果は？',code:'int a = 5;\na = 8;\nprintf("%d", a);',c:['5','8','13','エラー'],a:1,e:'a=8 で変数 a の中身が8に上書きされます。'}]},
{n:'Lv.1',title:'条件と繰り返し',desc:'if・for・while',qs:[
{q:'このコードは何回 Hello を表示する？',code:'for (int i=0; i<3; i++) {\n  printf("Hello\\n");\n}',c:['1回','2回','3回','4回'],a:2,e:'i は 0→1→2 と変化し、3になった時点で条件 i<3 が偽になります。'},
{q:'score=75 のとき表示されるのは？',code:'if(score >= 80) printf("A");\nelse if(score >= 60) printf("B");\nelse printf("C");',c:['A','B','C','何も表示されない'],a:1,e:'75は80以上ではありませんが60以上なので B が表示されます。'}]},
{n:'Lv.2',title:'配列と関数',desc:'配列・引数・return',qs:[
{q:'score[1] の値は？',code:'int score[3] = {70, 80, 90};',c:['70','80','90','1'],a:1,e:'Cの配列の添字は0から始まるので score[1] は2番目の80です。'},
{q:'add(3,5) の戻り値は？',code:'int add(int a,int b){\n  return a+b;\n}',c:['3','5','8','15'],a:2,e:'return a+b により 3+5=8 が呼び出し元へ返ります。'}]},
{n:'Lv.3',title:'中級C',desc:'ポインタ・文字列・構造体',qs:[
{q:'&a が表すものは？',c:['aの値','aのアドレス','aの型','aの名前'],a:1,e:'& はアドレス演算子で、変数がメモリ上のどこにあるかを表します。'},
{q:'構造体のメンバへアクセスする演算子は？',c:['::','.','&&','%%'],a:1,e:'通常の構造体変数では . を使います。ポインタ経由では -> を使います。'}]},
{n:'Lv.4',title:'穴埋め',desc:'コードの一部を完成',qs:[
{q:'1〜5を表示するため、??? に入る条件は？',code:'for(int i=1; ???; i++){\n  printf("%d ",i);\n}',c:['i < 5','i <= 5','i > 5','i == 5'],a:1,e:'1,2,3,4,5まで実行するには i<=5 が必要です。'}]},
{n:'Lv.5',title:'デバッグ',desc:'間違いを見つけて直す',qs:[
{q:'コンパイルエラーの原因は？',code:'int main(void){\n  int x = 10\n  printf("%d", x);\n  return 0;\n}',c:['mainがある','xが整数','セミコロン不足','returnがある'],a:2,e:'int x = 10 の末尾に ; が必要です。'}]},
{n:'Lv.6',title:'実装練習',desc:'自分で一部を書く',qs:[
{q:'整数 n を受け取り、2倍して返す関数 double_num を完成させてください。',type:'code',starter:'int double_num(int n)\n{\n    // ここを書く\n}',keys:['return','n','*','2'],e:'例：return n * 2; と書けば、nを2倍した値を呼び出し元へ返せます。'}]},
{n:'Lv.7',title:'コード全文チャレンジ',desc:'問題文から全部書く',qs:[
{q:'1から10までの整数の合計を計算し、その結果「55」を表示するCプログラムを最初から最後まで書いてください。',type:'code',starter:'',keys:['#include','stdio.h','main','for','printf'],e:'代表例は、sumを0で初期化し、for文で1〜10を加算して printf で表示する方法です。'}]}
];
let state;try{state=JSON.parse(localStorage.getItem('cstep'))}catch(e){};state=Object.assign({xp:0,correct:0,total:0,completed:{},streak:0,bestStreak:0},state||{});let li=0,qi=0,selected=null;
const $=id=>document.getElementById(id);function save(){localStorage.setItem('cstep',JSON.stringify(state))}function rank(){return state.xp>=500?'S':state.xp>=300?'A':state.xp>=150?'B':'C'}function rankInfo(){let r=rank(),min=r==='C'?0:r==='B'?150:r==='A'?300:500,max=r==='C'?150:r==='B'?300:r==='A'?500:500;return{r,p:r==='S'?100:Math.min(100,Math.round((state.xp-min)/(max-min)*100)),next:r==='S'?'最高ランク到達！':`次のランクまで ${max-state.xp} XP`}}function toast(t){let el=$('toast');el.textContent=t;el.classList.remove('hidden');setTimeout(()=>el.classList.add('hidden'),1800)}
function home(){ $('quiz').classList.add('hidden');$('home').classList.remove('hidden');let ri=rankInfo();$('heroRank').textContent=ri.r;$('xpBar').style.width=ri.p+'%';$('rankNext').textContent=ri.next;$('stats').innerHTML=`<div class=stat><div class=stat-icon>⚡</div><div><b>${state.xp}</b><small>XP</small></div></div><div class=stat><div class=stat-icon>🏆</div><div><b>${rank()}</b><small>ランク</small></div></div><div class=stat><div class=stat-icon>🎯</div><div><b>${state.total?Math.round(state.correct/state.total*100):0}%</b><small>正答率</small></div></div><div class=stat><div class=stat-icon>🔥</div><div><b>${state.bestStreak||0}</b><small>最高コンボ</small></div></div>`;let icons=['🌱','🔀','📦','🧠','🧩','🐞','🛠️','🚀'];$('levels').innerHTML=levels.map((l,i)=>`<button class=level onclick="start(${i})"><div class=level-icon>${icons[i]}</div><div><strong>${l.n} ${l.title}</strong><small>${l.desc}</small>${state.completed[i]?'<small class=done>✓ CLEAR</small>':''}</div><div class=level-no>${String(i+1).padStart(2,'0')}</div></button>`).join('')}
window.start=i=>{li=i;qi=0;show()};function show(){selected=null;let l=levels[li],q=l.qs[qi];$('home').classList.add('hidden');$('quiz').classList.remove('hidden');$('levelBadge').textContent=`${l.n} ${l.title}`;$('progress').textContent=`QUESTION ${qi+1} / ${l.qs.length}`;$('questionBar').style.width=((qi+1)/l.qs.length*100)+'%';$('streak').textContent=`🔥 ${state.streak||0} COMBO`;$('question').textContent=q.q;$('feedback').className='feedback hidden';$('nextBtn').classList.add('hidden');$('submitBtn').classList.remove('hidden');$('code').classList.toggle('hidden',!q.code);$('code').querySelector('code').textContent=q.code||'';$('choices').innerHTML='';$('answer').classList.add('hidden');if(q.type==='code'){$('answer').classList.remove('hidden');$('answer').value=q.starter||''}else{$('choices').innerHTML=q.c.map((x,i)=>`<button class=choice data-i=${i}>${String.fromCharCode(65+i)}：${x}</button>`).join('');document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{document.querySelectorAll('.choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selected=+b.dataset.i})}}
$('submitBtn').onclick=()=>{let q=levels[li].qs[qi],ok;if(q.type==='code'){let v=$('answer').value.toLowerCase();ok=q.keys.every(k=>v.includes(k.toLowerCase()))}else{if(selected===null){alert('回答を選んでください');return}ok=selected===q.a}state.total++;if(ok){state.correct++;state.xp+=20;state.streak=(state.streak||0)+1;state.bestStreak=Math.max(state.bestStreak||0,state.streak);toast(`正解！ +20 XP  🔥 ${state.streak} COMBO`)}else{state.streak=0}$('feedback').className='feedback '+(ok?'ok':'ng');$('feedback').innerHTML=`<strong>${ok?'正解！ 🎉':'もう一歩！'}</strong><br>${q.e}<br><b>${ok?'+20 XP':'XPは次の正解で獲得できます'}</b>`;save();$('submitBtn').classList.add('hidden');$('nextBtn').classList.remove('hidden')};
$('nextBtn').onclick=()=>{if(qi+1<levels[li].qs.length){qi++;show()}else{state.completed[li]=true;state.xp+=30;save();toast(`レベルクリア！ +30 XP / ランク ${rank()}`);setTimeout(home,500)}};$('backBtn').onclick=home;$('resetBtn').onclick=()=>{if(confirm('学習記録をすべてリセットしますか？')){localStorage.removeItem('cstep');location.reload()}};home();
